name: Contribution Snake Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: x7z9
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark
            assets/snake.gif?color_snake=#00F7FF&color_dots=#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./assets
          publish_branch: output
          commit_message: "🔄 Automated snake update [skip ci]"
